### ISSUE TITLE
Reading file into memory in chunks

### ISSUE THREAD

**Issue by kubkon** [golemfactory/sp-wasm#22]
Reading entire file at once limits your process to available RAM. I know we don't have such inputs yet, but it's trivial to use a loop and read and write file in chunks. It also doesn't force process to map new memory regions to store this file in memory. There is an optimal value for read size (to reduce syscalls overhead) for each OS and is user configurable on linux, maybe it's available in some crate.

_Originally posted by @mplebanski in https://github.com/golemfactory/sp-wasm/pull/20_

**Comment by mbenke** [comment]
Would it be possible to use `mmap`?

**Comment by kubkon** [comment]
@mbenke it probably would but I'm not sure if the benefit to cost ratio is in our favour here in terms of the work we'd need to do in order to integrate `mmap` with our current solution. I suggest we wait for WASI-compatible runtime such as `wasmtime` to stabilise and simply switch to it which already uses `mmap` internally.

Also, I don't think this issue is really true anymore since, by default, Rust internally buffers file reads. However, the problem remains on storing everything in RAM as it currently is in our sandbox. Anyhow, I'll close the issue for now, but feel free to re-open if you think we should do more work here, or whatnot. :-)
