### ISSUE TITLE
Error handling of input/output files configuration

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/sp-wasm#26]
## Description

**Golem Version**: current/develop

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu

**Branch** (if launched from source): develop

**Mainnet/Testnet**: Testnet

**Description of the issue**:

When writing my own gWasm task like Minimal Hamiltonian Path, I need to take care for putting the same file names in `task.json` and in the code. If configuration is mismatching, then the program execution ends with error. And that is good. The bad thing is that I do not know what went wrong - logs do not tell me this.

**Actual result**:

In stderr.log there is just `JavaScript error at :0:0 Uncaught exception: unknown (can't convert to string)`.

**Screenshots**:

## Steps To Reproduce
1. Take Minimal Hamiltonian Path use case.
2. The program writes output to the file `out.txt`.
3. Edit `task.json`.
4. Set output file path as out1.txt instead of out.txt.
5. Run task in Golem.
6. See log: `datadir1/rinkeby/ComputerRes/ae87e55e-9739-11e9-a94d-aaa91f9ae423/tmp/beddfc58-9739-11e9-80b3-aaa91f9ae423/stderr.log`.

## Expected behavior
Behaviour is correct, the info is wrong. The user does not know what went wrong.

## Logs and any additional context
stderr.log:
```[2019-06-25T11:09:50Z INFO  sp_wasm_engine::sandbox::engine] Initializing SpiderMonkey engine
[2019-06-25T11:09:50Z INFO  sp_wasm_engine::sandbox] Setting exec args [ '0', '3' ]
[2019-06-25T11:09:50Z INFO  sp_wasm_engine::sandbox] Loading input files at /golem/resources/in/subtask1
[2019-06-25T11:09:50Z INFO  sp_wasm_engine::sandbox] Running WASM /golem/resources/in/mhp.wasm
JavaScript error at :0:0 Uncaught exception: unknown (can't convert to string)
```

task.json
```
{
    "type": "wasm", 
    "name": "wasm", 
    "bid":  "1",
    "subtask_timeout": "00:10:00",
    "timeout": "00:10:00",
    "options": {
        "js_name": "mhp.js",
        "wasm_name": "mhp.wasm",
        "input_dir": "/home/lukaszglen/wasm_test_5/t2/in",
        "output_dir": "/home/lukaszglen/wasm_test_5/t2/out",
        "subtasks": {
            "subtask1": {
                "exec_args": ["0", "3"],
                "output_file_paths": ["out1.txt"]
            },
            "subtask2": {
                "exec_args": ["1", "3"],
                "output_file_paths": ["out2.txt"]
            },
            "subtask3": {
                "exec_args": ["2", "3"],
                "output_file_paths": ["out3.txt"]
            }
        }
    }
}
```

## Proposed Solution?
Clear info in stderr.log, like: Permission denied: out.txt, Access forbidden: out.txt etc.

There is more. In my case, I had to search for logs in Golem internals, tmp. Is there a way to make it more easly accessible? Is this a job for Brass team?

**Comment by kubkon** [comment]
Thanks for the report @lukasz-glen! The issue should be resolved now, and a way more informative error should be printed to screen. Please verify and if the issue persists, please reopen it here and cc me in! :-)
