### ISSUE TITLE
Verify sp-wasm builds in Docker

### ISSUE THREAD

**Issue by kubkon** [golemfactory/sp-wasm#42]
It has been reported that the `sp-wasm` doesn't build using Docker anymore. Need to verify this.

cc @badb

**Comment by badb** [comment]
```error: `/sp-wasm/sp-wasm-cli` does not contain a Cargo.toml file. --path must point to a directory containing a Cargo.toml file.```

I got the same error on Windows and on Linux.

**Comment by kubkon** [comment]
Cool, and thanks for the report!
